//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTI.Modules.SystemSettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTI.Modules.SystemSettings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow all sales.
        /// </summary>
        internal static string AllowAllSales {
            get {
                return ResourceManager.GetString("AllowAllSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sales larger than zero.
        /// </summary>
        internal static string AllowGreaterZero {
            get {
                return ResourceManager.GetString("AllowGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow zero dollar sales.
        /// </summary>
        internal static string AllowZeroSales {
            get {
                return ResourceManager.GetString("AllowZeroSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonDown {
            get {
                object obj = ResourceManager.GetObject("BlueButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueButtonUp {
            get {
                object obj = ResourceManager.GetObject("BlueButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow Void.
        /// </summary>
        internal static string DisallowVoid {
            get {
                return ResourceManager.GetString("DisallowVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sentinel pair is already in the list..
        /// </summary>
        internal static string DupSentinels {
            get {
                return ResourceManager.GetString("DupSentinels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid address..
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid channel name..
        /// </summary>
        internal static string EnterChannelName {
            get {
                return ResourceManager.GetString("EnterChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid channel number..
        /// </summary>
        internal static string EnterChannelNumber {
            get {
                return ResourceManager.GetString("EnterChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid charity name..
        /// </summary>
        internal static string EnterCharity {
            get {
                return ResourceManager.GetString("EnterCharity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid city..
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid code..
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid company name..
        /// </summary>
        internal static string EnterCompanyName {
            get {
                return ResourceManager.GetString("EnterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid contact name..
        /// </summary>
        internal static string EnterContactName {
            get {
                return ResourceManager.GetString("EnterContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid country..
        /// </summary>
        internal static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid license..
        /// </summary>
        internal static string EnterLicense {
            get {
                return ResourceManager.GetString("EnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid location name..
        /// </summary>
        internal static string EnterLocation {
            get {
                return ResourceManager.GetString("EnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid modem number..
        /// </summary>
        internal static string EnterModem {
            get {
                return ResourceManager.GetString("EnterModem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid operator name..
        /// </summary>
        internal static string EnterOperatorName {
            get {
                return ResourceManager.GetString("EnterOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid owner..
        /// </summary>
        internal static string EnterOwner {
            get {
                return ResourceManager.GetString("EnterOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid room name..
        /// </summary>
        internal static string EnterRoom {
            get {
                return ResourceManager.GetString("EnterRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid state..
        /// </summary>
        internal static string EnterState {
            get {
                return ResourceManager.GetString("EnterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Zip Code..
        /// </summary>
        internal static string EnterZip {
            get {
                return ResourceManager.GetString("EnterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is Busy.
        /// </summary>
        internal static string ErrorBusy {
            get {
                return ResourceManager.GetString("ErrorBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Communication Error.
        /// </summary>
        internal static string ErrorComm {
            get {
                return ResourceManager.GetString("ErrorComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value cannot be greater than the end value.
        /// </summary>
        internal static string ErrorGreaterThanEndValue {
            get {
                return ResourceManager.GetString("ErrorGreaterThanEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value has to be greater than the previous start value.
        /// </summary>
        internal static string ErrorLessThanPreviousStartValue {
            get {
                return ResourceManager.GetString("ErrorLessThanPreviousStartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value in the database for {0} is out of bounds.  The value will be set to {1}.
        /// </summary>
        internal static string ErrorLicenseFile {
            get {
                return ResourceManager.GetString("ErrorLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License File Error.
        /// </summary>
        internal static string ErrorLicenseFileHeader {
            get {
                return ResourceManager.GetString("ErrorLicenseFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered must be in the form of a decimal.
        /// </summary>
        internal static string ErrorMoney {
            get {
                return ResourceManager.GetString("ErrorMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Action.
        /// </summary>
        internal static string ErrorNoAuth {
            get {
                return ResourceManager.GetString("ErrorNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered must be a valid number.
        /// </summary>
        internal static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Parameter.
        /// </summary>
        internal static string ErrorParam {
            get {
                return ResourceManager.GetString("ErrorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered must be a valid percentage between 0 and 100.
        /// </summary>
        internal static string ErrorPercent {
            get {
                return ResourceManager.GetString("ErrorPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Server Response.
        /// </summary>
        internal static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Error.
        /// </summary>
        internal static string ErrorSql {
            get {
                return ResourceManager.GetString("ErrorSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Length Error.
        /// </summary>
        internal static string ErrorStringLen {
            get {
                return ResourceManager.GetString("ErrorStringLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Max cannot be lower than the Min .
        /// </summary>
        internal static string ErrorTransactionRange {
            get {
                return ResourceManager.GetString("ErrorTransactionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code : {0}.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer2.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve address information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetAddressDataFailed {
            get {
                return ResourceManager.GetString("GetAddressDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve channel information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetChannelDataFailed {
            get {
                return ResourceManager.GetString("GetChannelDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve charity information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetCharityDataFailed {
            get {
                return ResourceManager.GetString("GetCharityDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve company information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetCompanyDataFailed {
            get {
                return ResourceManager.GetString("GetCompanyDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve credit settings from the server. Reason: {0}.
        /// </summary>
        internal static string GetCreditEnabledFailed {
            get {
                return ResourceManager.GetString("GetCreditEnabledFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device fees from the server.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceFeesFailed {
            get {
                return ResourceManager.GetString("GetDeviceFeesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the device and/or machine id.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceInfoFailed {
            get {
                return ResourceManager.GetString("GetDeviceInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device settings from the server.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceSettingsFailed {
            get {
                return ResourceManager.GetString("GetDeviceSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve device information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetDeviceTypesFailed {
            get {
                return ResourceManager.GetString("GetDeviceTypesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve fun game information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetFunGameDataFailed {
            get {
                return ResourceManager.GetString("GetFunGameDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve location information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetLocationDataFailed {
            get {
                return ResourceManager.GetString("GetLocationDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve machine information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetMachineDataFailed {
            get {
                return ResourceManager.GetString("GetMachineDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve machine settings from server. Reason : {0}.
        /// </summary>
        internal static string GetMachineSettingsFailed {
            get {
                return ResourceManager.GetString("GetMachineSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve operator information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetOperatorDataFailed {
            get {
                return ResourceManager.GetString("GetOperatorDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve operator settings from the server.  Reason: {0}.
        /// </summary>
        internal static string GetOperatorSettingsFailed {
            get {
                return ResourceManager.GetString("GetOperatorSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get this machine&apos;s information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetSettingsFailed {
            get {
                return ResourceManager.GetString("GetSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your staff information from the server.  Reason: {0}.
        /// </summary>
        internal static string GetStaffDataFailed {
            get {
                return ResourceManager.GetString("GetStaffDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve your permissions from the server. Reason: {0}.
        /// </summary>
        internal static string GetStaffPermsFailed {
            get {
                return ResourceManager.GetString("GetStaffPermsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve system settings from the server.  Reason: {0}.
        /// </summary>
        internal static string GetSystemSettingsFailed {
            get {
                return ResourceManager.GetString("GetSystemSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GradientFull {
            get {
                object obj = ResourceManager.GetObject("GradientFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GradientPanel {
            get {
                object obj = ResourceManager.GetObject("GradientPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonDown {
            get {
                object obj = ResourceManager.GetObject("GreenButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenButtonUp {
            get {
                object obj = ResourceManager.GetObject("GreenButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System Settings module failed to initialize properly, and will now shut down. Check that GTI Server is running..
        /// </summary>
        internal static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid fee entered for device &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFee {
            get {
                return ResourceManager.GetString("InvalidFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TCP port!.
        /// </summary>
        internal static string InvalidMagCardPort {
            get {
                return ResourceManager.GetString("InvalidMagCardPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card track!.
        /// </summary>
        internal static string InvalidMagCardTrack {
            get {
                return ResourceManager.GetString("InvalidMagCardTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} response received from server..
        /// </summary>
        internal static string InvalidMessageResponse {
            get {
                return ResourceManager.GetString("InvalidMessageResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving this machine&apos;s information..
        /// </summary>
        internal static string LoadingMachineInfo {
            get {
                return ResourceManager.GetString("LoadingMachineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving operator information..
        /// </summary>
        internal static string LoadingOperatorInfo {
            get {
                return ResourceManager.GetString("LoadingOperatorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Player Center..
        /// </summary>
        internal static string LoadingPlayerCenter {
            get {
                return ResourceManager.GetString("LoadingPlayerCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving your information..
        /// </summary>
        internal static string LoadingStaffInfo {
            get {
                return ResourceManager.GetString("LoadingStaffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the log. Reason: {0}.
        /// </summary>
        internal static string LogFailed {
            get {
                return ResourceManager.GetString("LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard &amp; CPCL Printer (TCP).
        /// </summary>
        internal static string MagCardModeCPCLTCP {
            get {
                return ResourceManager.GetString("MagCardModeCPCLTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Only.
        /// </summary>
        internal static string MagCardModeKeyboard {
            get {
                return ResourceManager.GetString("MagCardModeKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.  The System Settings module will now shutdown.  Error: {0}.
        /// </summary>
        internal static string ModuleError {
            get {
                return ResourceManager.GetString("ModuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module intialization failed. Reason: {0}.
        /// </summary>
        internal static string ModuleInitFailed {
            get {
                return ResourceManager.GetString("ModuleInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All machines selected to edit must be of the same type.
        /// </summary>
        internal static string MultipleMachineEditError {
            get {
                return ResourceManager.GetString("MultipleMachineEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeButtonDown {
            get {
                object obj = ResourceManager.GetObject("OrangeButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrangeButtonUp {
            get {
                object obj = ResourceManager.GetObject("OrangeButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurpleButtonDown {
            get {
                object obj = ResourceManager.GetObject("PurpleButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PurpleButtonUp {
            get {
                object obj = ResourceManager.GetObject("PurpleButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonDown {
            get {
                object obj = ResourceManager.GetObject("RedButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedButtonUp {
            get {
                object obj = ResourceManager.GetObject("RedButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund In Cash.
        /// </summary>
        internal static string RefundInCash {
            get {
                return ResourceManager.GetString("RefundInCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Check.
        /// </summary>
        internal static string ReturnCheck {
            get {
                return ResourceManager.GetString("ReturnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChangesHeader {
            get {
                return ResourceManager.GetString("SaveChangesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes?.
        /// </summary>
        internal static string SaveChangesMessage {
            get {
                return ResourceManager.GetString("SaveChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single item must be selected for this operation..
        /// </summary>
        internal static string SelectSingleItem {
            get {
                return ResourceManager.GetString("SelectSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server communication lost..
        /// </summary>
        internal static string ServerCommFailed {
            get {
                return ResourceManager.GetString("ServerCommFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned error code: {0}.
        /// </summary>
        internal static string ServerErrorCode {
            get {
                return ResourceManager.GetString("ServerErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the channel information to the server.  Reason: {0}.
        /// </summary>
        internal static string SetChannelDataFailed {
            get {
                return ResourceManager.GetString("SetChannelDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the charity information to the server.  Reason: {0}.
        /// </summary>
        internal static string SetCharityDataFailed {
            get {
                return ResourceManager.GetString("SetCharityDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down....
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff not found..
        /// </summary>
        internal static string StaffNotFound {
            get {
                return ResourceManager.GetString("StaffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ted-E.
        /// </summary>
        internal static string Tablet {
            get {
                return ResourceManager.GetString("Tablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Negative Change.
        /// </summary>
        internal static string TenderModeAllow {
            get {
                return ResourceManager.GetString("TenderModeAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string TenderModeOff {
            get {
                return ResourceManager.GetString("TenderModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Negative Change.
        /// </summary>
        internal static string TenderModePrevent {
            get {
                return ResourceManager.GetString("TenderModePrevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn If Negative Change.
        /// </summary>
        internal static string TenderModeWarn {
            get {
                return ResourceManager.GetString("TenderModeWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string Tracker {
            get {
                return ResourceManager.GetString("Tracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler.
        /// </summary>
        internal static string Traveler {
            get {
                return ResourceManager.GetString("Traveler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveler II.
        /// </summary>
        internal static string Traveler2 {
            get {
                return ResourceManager.GetString("Traveler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save address information from the server.  Reason: {0}.
        /// </summary>
        internal static string UpdAddressDataFailed {
            get {
                return ResourceManager.GetString("UpdAddressDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save company information from the server.  Reason: {0}.
        /// </summary>
        internal static string UpdCompanyDataFailed {
            get {
                return ResourceManager.GetString("UpdCompanyDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save device fees to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdDeviceFeesFailed {
            get {
                return ResourceManager.GetString("UpdDeviceFeesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save location information to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdLocationDataFailed {
            get {
                return ResourceManager.GetString("UpdLocationDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save machine settings to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdMachineSettingsFailed {
            get {
                return ResourceManager.GetString("UpdMachineSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save operator information to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdOperatorDataFailed {
            get {
                return ResourceManager.GetString("UpdOperatorDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save operator settings to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdOperatorSettingsFailed {
            get {
                return ResourceManager.GetString("UpdOperatorSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save global system settings to the server.  Reason: {0}.
        /// </summary>
        internal static string UpdSystemSettingsFailed {
            get {
                return ResourceManager.GetString("UpdSystemSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonDown {
            get {
                object obj = ResourceManager.GetObject("YellowButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YellowButtonUp {
            get {
                object obj = ResourceManager.GetObject("YellowButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
